### ISSUE TITLE
BorrarHandle no me va

### ISSUE THREAD

**Issue by AitorDSG80** [AitorDSG80/practica_dwec_gestor_presupuesto#3]
Buenas @pedroprieto, estoy intentando que me funciona esta función de borrar y no consigo que vaya, ¿me puedes mirar el código a ver?

un saludo

**Comment by pedroprieto** [comment]
No tienes que preguntar nada:
https://github.com/AitorDSG80/practica_dwec_gestor_presupuesto/blob/3a3fea02ebb2730baafa2abc0e161c3a29bc1bf5/js/gestionPresupuestoWeb.js#L175

Directamente borrarlo:
https://github.com/AitorDSG80/practica_dwec_gestor_presupuesto/blob/3a3fea02ebb2730baafa2abc0e161c3a29bc1bf5/js/gestionPresupuestoWeb.js#L176

Pero pasando como parámetro `this.gasto.id`

**Comment by pedroprieto** [comment]
Perdona, he cometido un fallo en el comentario anterior. Ya está corregido.

**Comment by AitorDSG80** [comment]
Perfecto, he conseguido hacerlo y que funcione. Muchas gracias Pedro, voy a por la ultima. Me asusta un poco el examen ya que esto me cuesta muchas horas ir sacándolo.

**Comment by pedroprieto** [comment]
Poco a poco :wink: El examen lo tendrás chupao!! :laughing:

**Comment by AitorDSG80** [comment]
no se yo jejeje, ya tengo la practica terminada por si le puedes echar un vistacillo por si le falta algo, me pasa todos los test

**Comment by AitorDSG80** [comment]
Muchas gracias Pedro, la habia cerrado por que pensaba que ya no la mirarias, 

Lo reviso antes de hacerte la Pull Request y ya te la enviaré con ese cambio, no me da la vida con el curro jejjee

Un saludo !!!!!!

**Comment by pedroprieto** [comment]
Lo miro siempre todo. Lo único, que a veces se me acumulan los mensajes y tardo algo más en dar respuesta. Sobre todo después del fin de semana (lógicamente) :wink:

**Comment by pedroprieto** [comment]
Ten en cuenta que sois 40 matriculados... Y la mayoría aprovecháis el fin de semana para adelantar (también lógicamente).

Un saludo!!

**Comment by AitorDSG80** [comment]
Esta clarísimo, muchas gracias por contestar y tus comentarios ya que siempre me ayudan mucho a comprender y mejorar

**Comment by pedroprieto** [comment]
Me alegro!! :blush:
