### ISSUE TITLE
Duda Practica Formularios

### ISSUE THREAD

**Issue by AitorDSG80** [AitorDSG80/practica_dwec_gestor_presupuesto#4]
Buenas noches @pedroprieto,

tengo la practica en teoría hecha ya que me pasa todos los test pero tengo varias (muchísimas) dudas.

A la hora de activar el formulario en cada gasto y mostrar la fecha que tiene el gasto en el campo del formulario fecha, no consigo que se muestre automáticamente, a ver si me echas un cable con esto.

He sufrido mucho haciendo esta practica y hay cosas que me han salido a base de probar cosas que no entiendo muy bien, como por ejemplo la ultima parte de al darle al botón cancelar que activase otra vez el botón de editarFormulario, al final poniendo la función de repintar dentro del handle de cancelar he conseguido que funcione.

La verdad es que de cara al examen estoy acojonado ya que una cosa de estas en 2h no la saco ni en sueños, espero que pongas algo mas asequible.

Por favor si le puedes echar un ojo a mi código y darme opinión cuando puedas te lo agradecería.

Un saludo

**Comment by pedroprieto** [comment]
Buenas,

Acabo de subir el vídeo de la tutoría de hoy. En él trato de aclarar las dudas que planteas.

Un detalle que veo es este:
https://github.com/AitorDSG80/practica_dwec_gestor_presupuesto/blob/8a6c6d622146716198f3b11e12891ba31282c98e/js/gestionPresupuestoWeb.js#L203

No sé por qué le pasas el formulario. En su lugar deberías pasarle el gasto. En cuanto a la fecha, recuerda que `gasto.fecha` tiene guardado un timestamp, así que tendrás que ponerlo en el formulario en formato texto.

Echa un ojo al vídeo de hoy a ver si te aclara cosas!!

Un saludo,

Pedro Prieto

**Comment by AitorDSG80** [comment]
Buenas noches,

con tu comentario acabo de solucionar el tema de la fecha pasatndolo a un string con:
**new Date(this.gasto.fecha).toISOString().substr(0,10);**

El detalle de pasarle el formulario pues yo tampoco lo entiendo ahora muy bien ya que como te digo hay cosas que voy probando sin entender todo muy bien, he comentado la linea y sigue funcionando todo ok.

Mañana en tener un rato me veo la tutoría a ver si le saco algo mas aunque en principio ya la tengo terminada.

Me sigue asustando el examen y no se muy bien como estudiarme todo esto jejejej

Un saludo y gracias Pedro !!!

**Comment by pedroprieto** [comment]
Bien hecho!! Tranquilo con el examen, hombre :wink:

**Comment by AitorDSG80** [comment]
Pues parece que estaba equivocado, 

si comento la linea 203 o la 302, no me pasa los test, creo recordar que de esa manera lo hice por que le paso el formulario a los objetos del manejador(handle). A ver si me puedes echar un ojo bien a esos dos manejadores (EnviarGastoHandle y SubmitHandle) por si tuvieran algo mal pero creo que es necesario pasarles como propiedad el formulario.

Un saludo

**Comment by pedroprieto** [comment]
Revisa el video de la tutoría. Tu solución funciona bien, pero a lo mejor ves otra manera de hacerlo.

Un saludo!

**Comment by AitorDSG80** [comment]
Buenas,

pues ya lo he sacado, haciendo referencia al e.currentTarget dentro del manejador parece que no hace falta crearle la propiedad al objeto jejejeje

Échale un ojo cuando puedas a ver si estoy en lo cierto aunque mañana veré la tutoria

Un saludo

**Comment by pedroprieto** [comment]
Buenas,

Sí, `e.currentTarget` apunta al formulario, por eso no hace falta que se lo pases.

He visto que también creabas un formulario para añadir gastos. Eso no se pedía (solo era para editar), pero está perfecto :+1: De ahí venía mi confusión. En el de editar he visto que pasas el formulario y también el gasto (que no es necesario en el de añadir).

Un saludo!!
