### ISSUE TITLE
Duda con el botón cancelar para no usar repintar() (creo que resuelto)

### ISSUE THREAD

**Issue by AitorDSG80** [AitorDSG80/practica_dwec_gestor_presupuesto#5]
Buenas @pedroprieto,

he hecho la practica nueva y me gustaría que le echaras un ojo ya que aunque me pasa el test hay cosas que no se si estan hechas como se debería, me costó bastante entender el enunciado y la expresión regular utilizada me parece demasiado sencilla (no termino de entenderlas bien) aunque funciona.

Un saludo

**Comment by pedroprieto** [comment]
Buenas,

Le echo un ojo y lo miro en la PR.

Un saludo!

**Comment by AitorDSG80** [comment]
Tengo una duda ahí que no te he preguntado y me gustaria saber otra posible solucion.

No conseguí acceder al botón que había que volver a activar al pulsar cancelar, por ese motivo y tras estar probando varias cosas para intentar activar el botón desde el manejador de cancelar CancelarFormularioHandle, puse repintar() y con eso iba y pasaba los test.

Con e.currentTarget no me funciona o no se como hacerlo.

¿hay alguna manera de acceder al botón que hay que volver a activar sin repintar?

No se si me explico o sabes a que parte del código me refiero.

**Comment by AitorDSG80** [comment]
Vale,

investigando creo que he encontrado una solución, he creado otro manejador para el botón cancelar. Ahora tendríamos uno para el botón cancelar que sale cuando le damos al botón "Añadir gasto" y otro para el botón cancelar que saldría cuando le damos al botón "Editar (formulario)".

He conseguido hacer que se activen al darle al botón cancelar sin repintar, me he dado cuenta que se le puede pasar al evento el botón y después dentro de la función manejadora de cancelar activarlo o desactivarlo haciendo referencia al botón con this.

Si pudieras echarle un ojo cuando puedas te lo agradecería, he hecho commit.

Un saludo

**Comment by pedroprieto** [comment]
Es correcto. La solución pasa por hacer lo que has hecho: pasar una referencia al botón a través del objeto manejador de eventos.

Buen trabajo!!

**Comment by AitorDSG80** [comment]
Perfecto, gracias por mirarlo. Se me encendió la bombilla y dije voy a probar a ver y si que iba jejejejeje.

Un saludo
