### ISSUE TITLE
Error función cargarGastosApi

### ISSUE THREAD

**Issue by AitorDSG80** [AitorDSG80/practica_dwec_gestor_presupuesto#6]
Buenas Pedro @pedroprieto ,

no consigo hacer que me funcione esta función, a ver si puedes echarme un vistazo.

function cargarGastosApi(){

    let usuario = document.getElementById("nombre_usuario").value;
    let url = `https://suhhtqjccd.execute-api.eu-west-1.amazonaws.com/latest/${usuario}`;

    fetch(url, {
        method: 'GET',
        mode: 'no-cors',
    })
    .then(response => response.json())
    .then((result) => { 
        let resultado = result;
        console.log(result);
        gestionPresupuesto.cargarGastos(resultado);
        repintar();
    });
}

**Comment by AitorDSG80** [comment]
Vale al final me ha funcionado, la he hecho de dos maneras solo con fetch y otra con async await aunque veo mas limpia la primera

**Comment by AitorDSG80** [comment]
Tengo subidas las funciones borrarGastoApiHandle y cargarGastosApi, puedes echarles un ojo ya que no estoy seguro que la de borrar esté bien hecha?

**Comment by pedroprieto** [comment]
Muy buenas,

Parece que están bien. Comprueba que se borra bien accediendo a la API directamente :wink: 

Un saludo!

**Comment by AitorDSG80** [comment]
como puedo hacer esa prueba? no se muy bien como borrar algo de la api directamente, si me indicas como...... he probado a borrar en mi nombre ya que no hay nada y si devuelve lo que quiero pero no se si borraria si hubiera

**Comment by pedroprieto** [comment]
A ver, primero debes crear uno. Y luego, cuando lo tengas creado, borrarlo.

De todos modos ahora os pondré algún vídeo para interactuar con la API.

Un saludo!!

**Comment by pedroprieto** [comment]
Para crear uno debes implementar la funcionalidad correspondiente, claro...

**Comment by AitorDSG80** [comment]
si si, jajaja, esta tarde iba a ponerme a ello. A ver si lo consigo y pruebo el de borrar.

**Comment by pedroprieto** [comment]
:+1:
