### ISSUE TITLE
funciones realizadas

### ISSUE THREAD

**Issue by AitorDSG80** [AitorDSG80/practica_dwec_gestor_presupuesto#7]
Buenas @pedroprieto

he subido ya todas las funciones de la nueva practica, a ver si les puedes echar un ojillo rápido por si tengo algo mal o extraño y se puede mejorar. La aplicacion funciona bien tanto para añadir, cargar, borrar o editar. El nombre de mi url seria /aitorserna

Un saludo

**Comment by pedroprieto** [comment]
Tiene buena pinta. Lo único, creo que no es necesario pasar la referencia a los formularios: puedes acceder a ellos a través de [element.form](https://es.javascript.info/form-elements#referencia-inversa-element-form).

Un saludo!

**Comment by AitorDSG80** [comment]
Hola Pedro, te refieres a cogerlo con querySelector? o te refieres a otra forma? he mirando el enlace que me has pasado pero no acabo de entender como pillarlo sin el querySelector dentro de la función

**Comment by pedroprieto** [comment]
El manejador de evento puede acceder al elemento que lo ha generado (el botón). Y dicho botón, al estar dentro de un formulario, puede acceder al formulario que lo contiene (enlace que te he pasado).

**Comment by AitorDSG80** [comment]
te refieres a enviarGastoApi o a EditarGastoApi, o a las 2 funciones. Una la tengo como objeto manejador y la otra como manejador de eventos

**Comment by pedroprieto** [comment]
A todas.

**Comment by AitorDSG80** [comment]
Pues solo se me ocurre con el querySelector coger el form o no estoy entendiendo bien creo

**Comment by pedroprieto** [comment]
Con currentTarget en el evento llegas al botón. De ahí, al formulario. Y del formulario, a los campos.

**Comment by AitorDSG80** [comment]
Pero currentTarget no se puede usar en la de enviarGastoApi ya que no lleva como para metro el evento ni es del tipo handleEvent. O ya me estoy liando

**Comment by AitorDSG80** [comment]
bueno podria pasarle el event a la funcion y hacer algo asi e.currentTarget.form.descripcion

**Comment by AitorDSG80** [comment]
Funciona !!!!!! jajaja

**Comment by pedroprieto** [comment]
Claro!

**Comment by pedroprieto** [comment]
Todas las funciones manejadoras de eventos acceden al evento como parámetro. Incluidos las handleEvent de los objetos manejadores.

**Comment by AitorDSG80** [comment]
Pero hay que pasárselo como parámetro tal que así, no lo lleva implícito ¿no?

![image](https://user-images.githubusercontent.com/91147447/146579406-dc1ef9c4-fc58-4764-90c7-fe96bf20ede9.png)

**Comment by pedroprieto** [comment]
Claro. https://es.javascript.info/introduction-browser-events#objeto-del-evento

**Comment by pedroprieto** [comment]
Va implícito si lo asignas en HTML

**Comment by AitorDSG80** [comment]
si lo asignas directamente al evento en html puedes usar el event sin haberlo declarado previamente, es como si por detrás se construyese la función que lo declara en el parámetro. 

Pues he hecho el push con los cambios y funciona muy bien, cuando le puedas echar un ojo a ver si ahora si esta todo ok o se podría optimizar algo.

 Yo es que recordaba de otra practica que le podías pasar al evento cualquier cosa que estuviera en la función padre como propiedad (creo recordar que le pasaba al evento un botón para luego deshabilitarlo o habilitarlo en el manejador). Esto de JavaScript es super manejable de mil maneras.

**Comment by pedroprieto** [comment]
![Uploading IMG_20211217_180511.jpg…]()

**Comment by AitorDSG80** [comment]
Buenísimo esto Pedro, gracias por el tiempo de las respuestas y por la ayuda a comprender, me gusta mucho comprender que estoy haciendo siempre.

**Comment by pedroprieto** [comment]
Para eso estamos! 😊 

Te quería poner un pantallazo de la sección donde explica cómo se crea la función "por detrás", como tú dices. Está explicado en la sección https://es.javascript.info/introduction-browser-events#objeto-del-evento.

Es que con el móvil no me deja

**Comment by pedroprieto** [comment]
Textual:

> Esto es posible porque cuando el navegador lee el atributo, crea un handler como este: function(event) { alert(event.type) }. Lo que significa que el primer argumento es llamado "event" y el cuerpo es tomado del atributo.

**Comment by AitorDSG80** [comment]
si si jejejeje lo estaba leyendo y ahí me he dado cuenta de la manera que funciona, me parece muy interesante aprender y comprender este tipo de cosas. 

Sabiendo como funcionan las cosas por detrás a veces es mas "sencillo comprender" o resolver algo. Siempre con matices claro está ya que la teoría lleva muchísimas cosas bastante profundas que no me es fácil retener, pero supongo que a medida vas necesitando y usando pues se van comprendiendo.

**Comment by pedroprieto** [comment]
Claro. Comprender siempre paga dividendos...

Buem finde!

**Comment by AitorDSG80** [comment]
Es la clave jejeje, doy la practica por buena. Esta practica me ha gustado mucho la verdad.

Igualmente Pedro !!!!! Buen finde!!
