### ISSUE TITLE
Problema test con código practica graficas

### ISSUE THREAD

**Issue by AitorDSG80** [AitorDSG80/practica_dwec_gestor_presupuesto#8]
Buenas @pedroprieto

al realizar esta ultima práctica, me muestra las graficas bien, pero no me pasa el código los test de alguna de las prácticas anteriores.

Me puedes echar un ojo a ver cual es el motivo?

Un saludo y gracias de antemano

**Comment by pedroprieto** [comment]
Vale, el test 6 no sé por qué te falla... El test 8 sí: lo comenté en el vídeo de la tutoría. Al cargar los datos del almacenamiento local se vuelcan solo los datos, no se reconstruye el objeto. Por eso al modificar `repintar` y llamar a `obtenerPeriodoAgrupacion` sobre el objeto cargado desde el almacenamiento se produce un fallo y provoca el fallo del test.

Le daré una vuelta a ver si puedo solucionarlo...

Un saludo y gracias por el apunte!

**Comment by AitorDSG80** [comment]
He intentado mirar el resto de funciones a ver si podía corregir algo ya que han fallado justo al añadir el código, había hecho un commit previo cuando he añadido los scripts que has proporcionado en el html y se pasaban todos los test. Me da miedo tocar cosas y fastidiar las practicas anteriores.

A ver si sacas que puede ser y lo corrijo

Un saludo

**Comment by pedroprieto** [comment]
Vale, el test 6 te falla porque tienes un bug oculto:
https://github.com/AitorDSG80/practica_dwec_gestor_presupuesto/blob/2ce7427287050cfcbe7f76fdb7512f83efee5ef4/js/gestionPresupuesto.js#L45

Si la fecha que se pasa al crear el objeto no es válida, se genera una fecha incorrecta. Sí que compruebas en `actualizarFecha`, pero no al crear el objeto.

Ya tengo mejora para el test del año que viene :wink: 

El fallo del test 8 sí que es culpa mía. Sigo en ello...

**Comment by AitorDSG80** [comment]
Corregido lo del test 6, bug oculto solventado jejeje

A ver si das con el tema del 8 

Un saludo y muchas gracias siempre

**Comment by pedroprieto** [comment]
Solucionado. He puesto un mensaje en el foro de dudas y he actualizado el enunciado y el test de la práctica de almacenamiento. En cuanto lo corrijas funcionará bien. O eso espero :rofl: 

Un saludo!!

**Comment by AitorDSG80** [comment]
Buenas, he copiado la función que has puesto en la practica para cambiar la función cargarGastos y me sigue fallando el test8, no consigo dar con cual es el problema

A ver si me puedes ayudar

**Comment by AitorDSG80** [comment]
Problema solucionado !!!! otro bug oculto !!!!

**Comment by pedroprieto** [comment]
:+1:
